name: MMC-Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build dylib
        run: |
          clang++ -dynamiclib -o libmmc.dylib main.cpp

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: dylib
          path: libmmc.dylib
