name: MMC-Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install cmake

      - name: Build Dobby
        run: |
          mkdir -p build_dobby
          cd build_dobby
          cmake ../third_party/Dobby
          make -j$(sysctl -n hw.ncpu)

      - name: Inspect Dobby build output
        run: |
          ls -R build_dobby

      - name: Build dylib
        run: |
          clang++ -dynamiclib \
            main.cpp \
            -Ithird_party/Dobby/include \
            build_dobby/libdobby.a \
            -o libmmc.dylib

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: dylib
          path: libmmc.dylib